### ISSUE TITLE
Missing 'clocks' and 'time' modules

### ISSUE THREAD

**Issue by AngryLawyer** [jamesmunns/nrf52-hal#1]
Hi!
I'd like to start contributing to this crate, but don't want to duplicate effort.
Your last commit brought in references to 'clocks' and 'time' modules, but these files aren't in the repo - it's possible that you forgot to commit them?

**Comment by jamesmunns** [comment]
Most likely! Thanks for letting me know. I'm away from my PC for a couple hours, but I'll check as soon as possible.

**Comment by jamesmunns** [comment]
Hey @AngryLawyer, I pushed my current work, its still a bit of an ugly work in progress, let me know if something doesn't make sense or doesn't work for you!

**Comment by AngryLawyer** [comment]
Fantastic, cheers for this :)
