### ISSUE TITLE
[RFC] Wrap `nrf52::Peripherals` and `nrf52::CorePeripherals`

### ISSUE THREAD

**Issue by hannobraun** [jamesmunns/nrf52-hal#6]
The entry points to this crate's API are currently mostly extension traits: For a peripheral that this crate provides an API for, an extension trait is defined and implemented. Extension traits are implemented for the peripheral proxys from the `nrf52` crate. An extension trait defines a method like `constrain` or `split`, which consumes the raw peripheral proxy and returns the HAL API for that peripheral.

That style of API is popular among HAL APIs (I think mostly because most HAL crates start out by copying other HAL crates), but I believe it is flawed. The critical problem is, that the HAL can't control the initial hardware state, making it impossible to give certain guarantees without significant runtime overhead. If we knew for a fact that no one had been messing with the hardware before initializing the HAL API, we could give much stronger safety guarantees, without the additional runtime overhead.

So far this is a rather general argument, but there is one concrete problem that would be weird to solve with the extension trait style: On the nRF52, several groups of peripherals share the same address space, and only one peripheral in each group can be used at a time (see nRF52832 Product Specification, section 15.2).

If we controlled the initial hardware state, we could statically guarantee that the user can enable only one of the peripherals in a given address space at a time. With the the current architecture, I can only think of solutions that are weird (enabling one peripheral in the group consumes the others) or less efficient (check hardware status at runtime.

I propose the following architecture:
- We add a new struct, `Peripherals`, which wraps `nrf52::Peripherals` and `nrf52::CorePeripherals`.
- `Peripherals` has two methods that can be used to get an instance, `take` and `steal`.
- Under the hood, `take` and `steal` use the `take` and `steal` methods of `nrf52::Peripherals`/`nrf52::CorePeripherals` to provide the same guarantees that those methods provide.
- Each nRF52 peripheral is available as a field of `Peripherals`. For peripherals that don't have a HAL API implemented yet, the peripheral proxy from `nrf52` is provided directly.
- Each peripheral API provides a `free` method that returns the peripheral proxy from `nrf52`. This allows the user to fall back to the raw register API, if the HAL API doesn't fulfill their needs.
- This allows us to solve the problem of shared address spaces cleanly: We add singleton structs that represent the shared address spaces to `Peripherals`. Those are consumed by the HAL APIs of the shared peripherals when enabling them.

Summary: By following this architecture, we know that the user hasn't modified the hardware at the point when the HAL API is initialized (unless they have used `unsafe` means to do so, at which point all bets are off). This allows us to provide safety guarantees that we otherwise couldn't provide easily, or only with additional runtime overhead.

Further reading: I've been [using this technique in `lpc82x-hal`](https://github.com/braun-robotics/rust-lpc82x-hal/blob/98f47969e6457521a28b54ab962a2cb1ad755a53/src/lib.rs#L253) for a while now, and I'm very happy with it. One major problem it solves is pin function assignment. `lpc82x-hal` statically guarantees that conflicting pin functions can't be assigned to a single pin. Without control over the initial hardware conditions, this could not be achieved without checking every single function assignment register (nRF52 has the same problem, by the way).

**Comment by hannobraun** [comment]
Something I noticed today: The pins in `gpio::p0::Parts` have the initial state `Input<Floating>`. This is the default, but if the user has done anything with P0 before calling `split`, this could be plainly wrong. If my proposal were implemented, this could stay as it is. Otherwise, we need to add an additional `Unknown` state.

**Comment by jamesmunns** [comment]
Hey Hanno,

I'm not totally sure if I am grokking the motivation for another layer of struct abstraction. Are you looking to do something like this?

```rust
// note, not the same as raw::Spim
struct Spim {
    fn new(raw::Spim, pins: Pins) -> Self {
        // do some init...
    }
    fn free(self) -> Spi {
        Spi::new()
    }
}


struct Spi {
    spim: raw::Spim,
    spis: raw::Spis,
}
impl Spi {
    fn into_spim(self, pins: Pins) -> Spim {
        Spim::new(self.spim, pins)
    }
    // ...
}
struct Peripheral {
    timer: Timer,
    spi: Spi,
    // ...
}
```

In general the idea here is that we are adding a "HalPeripherals" struct really, and "hiding" the "RawPeripherals" from the user (or at least discouraging direct use)?

**Comment by hannobraun** [comment]
> I'm not totally sure if I am grokking the motivation for another layer of struct abstraction.

Well, the motivation is to take control of the hardware *before* the user had a chance to mess with it. I think that's the only reasonable way to provide some static guarantees. To restate some examples from my previous comments:
- Prevent peripherals that share the same address space from interfering with each other. How else can we even do this? Check the value of the `ENABLED` register at the beginning of each peripheral API method, return an error, if it has an unexpected value?
- Fix the static guarantees of the pin API. If the user sets a pin to output mode, then calls `P0.split()` they get a pin stating it's in input mode when it really isn't, which defeats the point of having that type state in the first place. Granted, you can fix this by having the pins start out in an `Unknown` state.
- Pin assignment to peripheral functions. What happens if the user assigns pins to peripheral A using the raw API, then initializes the HAL API and uses it to assign the same pins to peripheral B? Again, the static guarantees are easily circumvented, so what is the point of having them in the first place? And this case is not easily fixed with some kind of `Unknown' initial state, as you'd have to inspect the pin assignment registers of all relevant peripherals to ensure that a pin is actually available for assignment (which is quite a bit of runtime overhead and adds an error condition that must be handled).

And I'm sure, as we build out this crate, there will be many more cases where we can't easily uphold static guarantees without being sure that the user didn't change anything before the HAL API took over. Yes, often there is an alternative solution:
- Don't rely on initial pin mode, just force the user to overwrite the mode bit before using the pin (a little runtime overhead).
- Don't rely on the pin not being assigned to a peripheral, just check all relevant pin assignment registers before allowing the user to use the pin (quite a bit more runtime overhead).
- Start out everything that has a type state in an unknown state, and have the user call an `unsafe fn yes_i_promise_i_did_not_mess_with_this` method before transitioning to a state that provides anything useful.

I explored all those approaches in lpc82x-hal, and all have their own problems. Adding that wrapper around `Peripherals`/`CorePeripherals` solved all those problems once and for all, in a zero-cost way.

> Are you looking to do something like this?

That looks like one way to solve the problem of shared peripheral spaces. I was thinking more along the lines of adding a singleton struct for each shared address space to the `Peripherals` wrapper, and consume those singleton structs in the `enable` method of the peripherals that share that space.

But that's really not the point. The point is, once we can rely on the fact that the initial conditions documented in the product spec are actually the conditions we find when we take control of the hardware, it's straight-forward to find a solution that guarantees correctness, regardless of whether that solution looks like yours or like mine.

> In general the idea here is that we are adding a "HalPeripherals" struct really, and "hiding" the "RawPeripherals" from the user (or at least discouraging direct use)?

To me it's not about hiding or discouraging. If you look at lpc82x-hal, all raw peripheral APIs are either exposed directly through the `lpc82x_hal::Peripherals` struct (for peripherals that have no HAL API), or they are available through a `free` method of the peripheral API.

The point is to use our knowledge of the initial hardware conditions to uphold static correctness guarantees. If the user decides they don't want those guarantees, I won't stand in their way of accessing the peripheral directly. But if we let them access the peripherals directly *before* the HAL API takes over, we will no longer be able to uphold those correctness guarantees.

**Comment by hannobraun** [comment]
Closing in favor of https://github.com/nrf-rs/nrf52/issues/7.
