### ISSUE TITLE
[RFC] Change the way pin types are generated

### ISSUE THREAD

**Issue by hannobraun** [jamesmunns/nrf52-hal#8]
Most of the code in the GPIO module is generated using a macro, including all the types that represent pins. Through my experience working on [lpc82x-hal](https://github.com/braun-robotics/rust-lpc82x-hal), I've come to regard this as an anti-pattern.

To be clear, I'm not suggesting that we don't generate code using a macro. I'm suggesting that we minimize the amount of generated code, using it only to feed platform-specific bits into generic, hand-written code.

But more on my suggestion later. First, the reasons on why I regard generating everything (specifically all pin types) as an anti-pattern:
1. It makes the code hard to read. If you're unfamiliar with the code and need to make sense of something, you constantly have to correlate the code in the macro, to the macro's argument list, to the macro invocation.
2. The generated pin types represent two different concepts: Which pin this is, and what mode it is in. Combining these two things in the way that is done with the pin types violates the single responsibility principle.

Argument 1. is fairly self-evident, but argument 2. might seem a bit a bit esoteric. It does have real consequences, however. Consider a wrapper type around a pin that is generic over the pin, but specific about the state. Currently, this would require higher-kinded types to express:
``` rust
struct PinWrapper<T>(T<Output<PushPull>>);
```

Since higher-kinded types don't exist in Rust, you'd have to use the generic pin type, making the wrapper type less type-safe than it could be:
``` rust
struct PinWrapper(P0_Pin<Output<PushPull>>);
```

See [dwm1001](https://github.com/braun-robotics/rust-dwm1001/blob/34f19d47645266f6aeb8b9f1bd20a7d4e2a4651f/src/lib.rs#L588) for a real-life example of this problem.

I've encountered this same problem with lpc82x-hal and came up with the following solution:
1. Pull as much code as possible out of the macro, into generic, hand-written types.
2. Use traits to abstract over the non-generic parts of the implementation.
3. Use a macro to generate types that implement those traits.

This would look something like this. First, the generic `Pin` type:
``` rust
struct Pin<T, Mode> { ... }
```

`Pin` relies on traits to do whatever it needs to do:
``` rust
impl<T> Pin<T, Output> where T: PinTrait {
    pub fn do_stuff(&mut self) {
        T::do_stuff();
    }
}
```

A code generation macro would still exist, but it would only generate the bare minimum: Types like `P0_12` and their trait implementations. lpc82x-hal has several implementations of this pattern: [Pin](https://github.com/braun-robotics/rust-lpc82x-hal/blob/98f47969e6457521a28b54ab962a2cb1ad755a53/src/swm.rs#L469), [Function](https://github.com/braun-robotics/rust-lpc82x-hal/blob/98f47969e6457521a28b54ab962a2cb1ad755a53/src/swm.rs#L758)

Now type of pin and mode of pin are cleanly separated, and all combinations can be cleanly expressed:
``` rust
struct FullyGeneric<T, Mode>(Pin<T, Mode>);
struct TypeGeneric<T>(Pin<T, Output>);
struct ModeGeneric<Mode>(Pin<P0_12, Mode>);
struct FullySpecific(Pin<P0_12, Output);
```

`P0_Pin` and `degrade` would no longer be necessary.

There's one drawback that I never found a good solution for: Whereever you implement this pattern, you end up with a struct, e.g. `Thing` and a trait that really wants to have the same name. I've been calling these traits `ThingTrait` instead. This is not pretty, but okay. I'm open to any suggestions!

**Comment by jamesmunns** [comment]
I don't have any strong feelings, I would say go for it.

**Comment by hannobraun** [comment]
Closing in favor of https://github.com/nrf-rs/nrf52/issues/8.
